---
network_fqdn: "{{ inventory_hostname }}.sneaky.nonroutable.network"

network_output_policy: ACCEPT

xbps_repository_address: repo-fastly.voidlinux.org
xbps_repository_main: "https://{{ xbps_repository_address }}/current/musl"
xbps_repository_nonfree: "{{xbps_repository_main }}/nonfree"
xbps_repository_port: 443

xbps_repoconf_repos_enabled:
  - 00-repository-main
  - 10-repository-nonfree
