---
- hosts: fleet
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - xbps-repoconf
    - void.network.dns
    - mmc_drivers
    - sddm
    - sddm_theme_omnigreeter
    - chrony
    - maldridge_dots
