---
- name: Install Graphical Environments - i3
  community.general.xbps:
    pkg:
      - i3
      - i3status
      - dmenu
    state: present

- name: Install Common Packages
  community.general.xbps:
    pkg:
      - arandr
      - caffeine-ng
      - dumb_runtime_dir
      - emacs
      - evince
      - feh
      - firefox
      - flameshot
      - guvcview
      - htop
      - mpv
      - pavucontrol
      - pipewire
      - rxvt-unicode
      - tmux
      - tree
      - urxvt-perls
      - vinagre
      - vlc
      - wireplumber
      - x11vnc
    state: present

- name: Remove i3 debug from logins
  ansible.builtin.file:
    path: /usr/share/xsessions/i3-with-shmlog.desktop
    state: absent
