---
- name: Install Graphical Environments - i3
  community.general.xbps:
    pkg:
      - i3
      - i3status
      - dmenu
    state: present

- name: Install Common Packages
  community.general.xbps:
    pkg:
      - arandr
      - caffeine-ng
      - dumb_runtime_dir
      - emacs
      - evince
      - feh
      - firefox
      - flameshot
      - guvcview
      - htop
      - mpv
      - pavucontrol
      - pipewire
      - rxvt-unicode
      - tmux
      - tree
      - urxvt-perls
      - vinagre
      - vlc
      - wireplumber
      - x11vnc
    state: present

- name: Remove i3 debug from logins
  ansible.builtin.file:
    path: /usr/share/xsessions/i3-with-shmlog.desktop
    state: absent

- name: Create /etc/pipewire/pipewire.conf.d
  ansible.builtin.file:
    path: /etc/pipewire/pipewire.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Enable Wireplumber
  ansible.builtin.file:
    src: /usr/share/examples/wireplumber/10-wireplumber.conf
    dest: /etc/pipewire/pipewire.conf.d/10-wireplumber.conf
    state: link

- name: Enable Pipewire-Pulse
  ansible.builtin.file:
    src: /usr/share/examples/pipewire/20-pipewire-pulse.conf
    dest: /etc/pipewire/pipewire.conf.d/20-pipewire-pulse.conf
    state: link
