---
- name: Add Network
  ansible.builtin.template:
    src: network.conf.j2
    dest: /etc/wpa_supplicant/conf.d/10-{{ ssid }}.conf
    owner: root
    group: root
    mode: "0640"
  notify: wpa_supplicant.conf
