---
- hosts: nomad_server
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - nomad-server
    - nomad-client

- hosts: nomad_client
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - nomad-client
