---
ansible_host: 172.16.31.3

nomad_volumes:
  - name: pitman_redis
    path: /nomad/pidman_redis
    read_only: false
  - name: filespace_cfg
    path: /nomad/filespace_cfg
    read_only: false
  - name: filespace_data
    path: /nomad/filespace_data
    read_only: false
