---
- name: Install Packages
  xbps:
    pkg: docker
    state: present

- name: Enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Install Client Config
  template:
    src: 20-client.hcl.j2
    dest: /etc/nomad.d/20-client.hcl
    owner: root
    group: root
    mode: 0644
  notify:
    - nomad

- name: Create any missing directories
  file:
    path: "{{item.path}}"
    state: directory
  with_items: "{{nomad_volumes|default([])}}"
  loop_control:
    label: "{{item.name}}"
